---
version: '3'
services:
  lskypro:
    image: coldpig/lskypro-docker:latest
    restart: unless-stopped
    hostname: lskypro
    container_name: lskypro
    volumes:
      - /data/lsky_pro/html:/var/www/html
    ports:
      - "9080:80"

  lskypro_mysql:
    image: mysql:5.7.37
    restart: unless-stopped
    # 主机名，可作为子网域名填入安装引导当中
    hostname: lskypro_mysql
    # 容器名称
    container_name: lskypro_mysql
    # 修改加密规则
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /data/lsky_pro/mysql/data:/var/lib/mysql
      - /data/lsky_pro/mysql/conf:/etc/mysql
      - /data/lsky_pro/mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyPassword # 数据库root用户密码
      MYSQL_DATABASE: lskypro # 给lsky-pro用的数据库名称

  lskypro_adminer:
    image: adminer:latest
    container_name: lskypro_adminer
    hostname: lskypro_adminer
    restart: unless-stopped
    ports:
      - 18080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=lskypro_mysql

  lskypro_redis:
    image: redis:latest
    container_name: lskypro_redis
    hostname: lskypro_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /data/lsky_pro/redis/redis.conf:/etc/redis/redis.conf 
      - /data/lsky_pro/redis/data:/data
    command: redis-server /etc/redis/redis.conf
